sudo: required

language: go

services:
  - docker

before_install:
  - docker login -u lynxluna -p ${DOCKER_PASSWORD}
  - docker pull golang:alpine

script:
  - docker build -f golang/Dockerfile -t ykode/golang-builder .
  - docker push ykode/golang-builder

